/* ============================================================
   HOLO·LAB — ENGINEERING ASSET LIBRARY
   ------------------------------------------------------------
   Every asset used in electronics + mechanical engineering.
   `sim` keys map to validators in js/simulator.js.
   `icon` returns inline SVG (48x48 viewBox) in hologram style.
   ============================================================ */
const C = '#00e5ff';
const S = { stroke: C, fill: 'none', 'stroke-width': 2.4 };
const SF = { stroke: C, fill: 'rgba(0,229,255,0.14)', 'stroke-width': 2.4 };

const P = (attrs) => {
  const s = Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ');
  return `<path ${s}/>`;
};
const R = (attrs) => {
  const s = Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ');
  return `<rect ${s}/>`;
};
const L = (x1, y1, x2, y2) => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" ${Object.entries(S).map(([k, v]) => `${k}="${v}"`).join(' ')}/>`;

const ICONS = {
  battery: () => R({ ...SF, x: 15, y: 14, width: 18, height: 22, rx: 2 }) + L(24, 8, 24, 14) + L(24, 8, 27, 8) + R({ ...S, x: 19, y: 20, width: 10, height: 6 }) + R({ ...S, x: 19, y: 28, width: 10, height: 3 }),
  resistor: () => P({ ...S, d: 'M8 24 h5 l3 -7 3 14 3 -14 3 14 3 -7 h5' }),
  capacitor: () => L(14, 24, 20, 24) + L(14, 24, 20, 24) + L(28, 24, 34, 24) + L(20, 16, 20, 32) + L(28, 16, 28, 32),
  led: () => L(6, 24, 14, 24) + P({ ...S, d: 'M14 17 L28 24 L14 31 Z' }) + L(28, 17, 28, 31) + L(34, 24, 42, 24) + P({ ...S, d: 'M37 16 l5 0 0 5' }) + P({ ...S, d: 'M41 18 l5 0 0 5' }),
  diode: () => P({ ...S, d: 'M8 24 L22 24 L8 40 L22 24 L8 8 Z' }) + L(22, 12, 22, 36) + L(6, 24, 12, 24) + L(28, 24, 42, 24),
  transistor: () => L(24, 10, 24, 20) + L(24, 38, 24, 26) + L(10, 40, 38, 40) + L(10, 40, 10, 26) + L(38, 40, 38, 26) + L(10, 26, 38, 26) + L(14, 32, 34, 32),
  switch: () => L(8, 26, 20, 26) + L(30, 26, 40, 26) + L(16, 16, 34, 26) + L(20, 26, 20, 22) + L(30, 26, 30, 22) + L(20, 22, 30, 22),
  fuse: () => R({ ...S, x: 16, y: 16, width: 16, height: 16 }) + L(16, 24, 24, 24) + L(24, 24, 24, 18) + L(8, 24, 16, 24) + L(32, 24, 40, 24),
  inductor: () => L(8, 24, 14, 24) + L(34, 24, 40, 24) + P({ ...S, d: 'M14 20 a5 5 0 0 1 0 8 a5 5 0 0 1 0 -8 a5 5 0 0 1 0 8 a5 5 0 0 1 0 -8 a5 5 0 0 1 0 8' }),
  motor: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 12 }) + L(24, 24, 16, 16) + L(24, 24, 30, 18) + L(24, 24, 24, 10) + L(24, 12, 28, 8) + L(24, 12, 20, 8),
  buzzer: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 12 }) + P({ ...S, d: 'M18 22 a6 6 0 0 0 0 8' }) + P({ ...S, d: 'M23 18 a10 10 0 0 0 0 12' }) + P({ ...S, d: 'M28 24 l6 0 0 5' }),
  speaker: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 12 }) + P({ ...S, d: 'M16 26 a8 8 0 0 1 0 -8' }) + P({ ...S, d: 'M22 30 a13 13 0 0 0 0 -16' }),
  relay: () => R({ ...S, x: 8, y: 14, width: 20, height: 20 }) + L(18, 20, 18, 24) + L(18, 20, 14, 17) + L(32, 24, 40, 24) + L(8, 24, 4, 24) + L(18, 34, 14, 38),
  button: () => R({ ...S, x: 14, y: 14, width: 20, height: 20, rx: 10 }) + L(24, 10, 24, 14) + L(24, 34, 24, 38) + L(8, 24, 14, 24) + L(34, 24, 40, 24),
  potentiometer: () => P({ ...S, d: 'M6 24 h4 l3 -7 3 14 3 -14 3 14 3 -7 h4' }) + P({ ...S, d: 'M19 10 l4 12 -5 -4' }) + L(6, 24, 4, 24) + L(26, 24, 42, 24),
  ldr: () => R({ ...SF, x: 14, y: 14, width: 20, height: 20, rx: 4 }) + L(24, 18, 24, 30) + L(18, 24, 30, 24) + L(20, 20, 28, 28) + L(8, 24, 14, 24) + L(34, 24, 40, 24),
  seg7: () => R({ ...S, x: 12, y: 10, width: 24, height: 28, rx: 2 }) + P({ ...S, d: 'M16 16 h16 M16 24 h16 M16 32 h16 M18 18 v4 M30 18 v4 M18 26 v4 M30 26 v4' }),
  ic: () => R({ ...SF, x: 12, y: 14, width: 24, height: 20 }) + P({ ...S, d: 'M18 20 a2 2 0 1 0 0.01 0' }) + L(12, 20, 6, 20) + L(12, 28, 6, 28) + L(36, 20, 42, 20) + L(36, 28, 42, 28),
  mcu: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24 }) + P({ ...S, d: 'M18 18 h12 M18 24 h12 M18 30 h12' }) + L(12, 18, 6, 18) + L(12, 24, 6, 24) + L(36, 18, 42, 18),
  crystal: () => R({ ...S, x: 14, y: 20, width: 20, height: 8 }) + L(14, 24, 8, 24) + L(34, 24, 40, 24),
  regulator: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 2 }) + L(12, 18, 6, 18) + L(24, 36, 24, 42) + L(36, 18, 42, 18) + L(30, 30, 18, 30),
  transformer: () => L(24, 8, 24, 18) + L(24, 30, 24, 40) + P({ ...S, d: 'M18 18 a6 6 0 0 1 0 12 a6 6 0 0 1 0 -12' }) + P({ ...S, d: 'M30 18 a6 6 0 0 1 0 12 a6 6 0 0 1 0 -12' }) + L(18, 24, 6, 24) + L(30, 24, 42, 24),
  antenna: () => P({ ...S, d: 'M24 8 L24 22 M24 12 L30 18 M24 16 L18 22 M24 20 L30 26' }) + P({ ...S, d: 'M20 28 h8 M22 34 h4' }),
  servo: () => R({ ...SF, x: 12, y: 10, width: 24, height: 28 }) + R({ ...S, x: 20, y: 24, width: 8, height: 14 }) + L(24, 24, 24, 20) + L(24, 10, 24, 8) + L(16, 38, 16, 42) + L(24, 38, 24, 42) + L(32, 38, 32, 42),
  display: () => R({ ...SF, x: 8, y: 10, width: 32, height: 28, rx: 3 }) + R({ ...S, x: 14, y: 16, width: 20, height: 16 }) + L(14, 21, 34, 21) + L(14, 26, 34, 26),
  gear: () => {
    let s = R({ ...S, x: 20, y: 20, width: 8, height: 8 });
    for (let i = 0; i < 12; i++) { const a = (i * 30 * Math.PI) / 180; s += L(24 + 10 * Math.cos(a), 24 + 10 * Math.sin(a), 24 + 14 * Math.cos(a), 24 + 14 * Math.sin(a)); }
    return s;
  },
  gearLarge: () => {
    let s = R({ ...S, x: 19, y: 19, width: 10, height: 10 });
    for (let i = 0; i < 16; i++) { const a = (i * 22.5 * Math.PI) / 180; s += L(24 + 11 * Math.cos(a), 24 + 11 * Math.sin(a), 24 + 15 * Math.cos(a), 24 + 15 * Math.sin(a)); }
    return s;
  },
  shaft: () => R({ ...S, x: 6, y: 18, width: 36, height: 12, rx: 6 }) + R({ ...S, x: 20, y: 14, width: 8, height: 20 }),
  bearing: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 12 }) + R({ ...SF, x: 20, y: 20, width: 8, height: 8, rx: 4 }) + P({ ...S, d: 'M12 24 h6 M30 24 h6 M24 12 v6 M24 30 v6' }),
  spring: () => L(10, 24, 16, 24) + P({ ...S, d: 'M16 14 l5 10 -5 10 5 10 -5 10' }) + L(16, 34, 38, 34) + L(21, 24, 38, 24),
  pulley: () => R({ ...SF, x: 12, y: 12, width: 24, height: 24, rx: 12 }) + R({ ...SF, x: 20, y: 20, width: 8, height: 8, rx: 4 }),
  pulleyLarge: () => R({ ...SF, x: 8, y: 8, width: 32, height: 32, rx: 16 }) + R({ ...SF, x: 20, y: 20, width: 8, height: 8, rx: 4 }),
  belt: () => P({ ...S, d: 'M10 24 a14 14 0 0 1 28 0 a14 14 0 0 1 -28 0' }),
  bolt: () => P({ ...S, d: 'M24 8 L34 14 L34 34 L24 40 L14 34 L14 14 Z' }) + L(24, 8, 24, 40) + L(14, 14, 34, 34),
  chassis: () => R({ ...SF, x: 6, y: 8, width: 36, height: 32, rx: 2 }) + L(6, 16, 42, 16) + L(6, 26, 42, 26) + L(14, 8, 14, 40),
  piston: () => R({ ...S, x: 10, y: 16, width: 12, height: 16 }) + L(22, 24, 36, 24) + L(36, 20, 42, 24) + L(36, 28, 42, 24),
  linkage: () => R({ ...S, x: 8, y: 21, width: 32, height: 6 }) + R({ ...SF, x: 5, y: 18, width: 6, height: 6, rx: 3 }) + R({ ...SF, x: 37, y: 18, width: 6, height: 6, rx: 3 }),
  hinge: () => P({ ...S, d: 'M12 40 A18 18 0 0 1 30 40' }) + L(12, 40, 12, 24) + L(30, 40, 30, 24) + R({ ...SF, x: 9, y: 18, width: 6, height: 6, rx: 3 }) + R({ ...SF, x: 27, y: 18, width: 6, height: 6, rx: 3 }),
  coupling: () => R({ ...S, x: 8, y: 18, width: 32, height: 12, rx: 2 }) + R({ ...SF, x: 18, y: 14, width: 4, height: 20 }) + R({ ...SF, x: 26, y: 14, width: 4, height: 20 }),
  cam: () => P({ ...SF, d: 'M24 14 L34 30 L14 30 Z' }) + R({ ...SF, x: 20, y: 20, width: 8, height: 8, rx: 4 }),
  gearbox: () => R({ ...SF, x: 8, y: 12, width: 32, height: 24, rx: 3 }) + L(24, 12, 24, 36) + L(8, 24, 40, 24) + R({ ...SF, x: 18, y: 20, width: 12, height: 12, rx: 6 }),
  washer: () => R({ ...SF, x: 15, y: 15, width: 18, height: 18, rx: 9 }) + R({ ...SF, x: 21, y: 21, width: 6, height: 6, rx: 3 }),
  joint: () => R({ ...SF, x: 10, y: 10, width: 28, height: 28, rx: 14 }) + P({ ...S, d: 'M24 10 a14 14 0 0 0 0 28' }) + L(24, 24, 38, 24),
  motorMount: () => R({ ...SF, x: 8, y: 14, width: 32, height: 20, rx: 2 }) + L(8, 20, 40, 20) + R({ ...SF, x: 18, y: 8, width: 12, height: 6, rx: 2 }),
  leadScrew: () => L(6, 16, 42, 16) + L(6, 32, 42, 32) + L(12, 16, 12, 32) + L(22, 16, 22, 32) + L(32, 16, 32, 32) + L(42, 16, 42, 32)
};

export const ASSETS = [
  // ============ ELECTRONICS ============
  { id: 'battery', cat: 'electronics', name: 'Battery Cell', w: 2, h: 1, icon: 'battery', sim: 'battery',
    desc: 'Stores chemical energy and supplies DC voltage to the whole circuit.',
    how: 'Chemical reaction between anode and cathode pushes electrons around the loop — the energy backbone of the device.',
    spec: '1.5–12 V, e.g. 3.7 V Li-ion / 9 V PP3',
    fail: 'Removed or drained → total power loss; every component goes dead.',
    pins: [{ id: '+', x: 2, y: 0.5 }, { id: '-', x: 0, y: 0.5 }] },
  { id: 'resistor', cat: 'electronics', name: 'Resistor', w: 2, h: 1, icon: 'resistor', sim: 'resistor',
    desc: 'Limits current flow and sets voltage drops; the protection element of every LED and IC.',
    how: 'Converts excess energy to heat; obeys Ohm\'s law V = I × R.',
    spec: 'Ohms Ω (E12 series: 10 Ω – 1 MΩ), power 0.25 W',
    fail: 'Removed → over-current damages downstream parts. Short → smoke.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'capacitor', cat: 'electronics', name: 'Capacitor', w: 2, h: 1, icon: 'capacitor', sim: 'capacitor',
    desc: 'Stores charge to smooth voltage ripple and filter noise on the power rail.',
    how: 'Two plates separated by a dielectric store charge; charges when voltage is high, discharges when it dips.',
    spec: '10 nF – 1000 µF, working voltage 16–400 V',
    fail: 'Removed → voltage ripple, LED flicker, IC noise. Reversed → ruptures.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'led', cat: 'electronics', name: 'LED', w: 2, h: 1, icon: 'led', sim: 'led',
    desc: 'Light-emitting diode — the visual output that shows a circuit is alive.',
    how: 'Electrons recombine with holes, releasing photons. Needs a current-limiting resistor!',
    spec: 'Fwd drop 1.8–3.3 V, max 20 mA',
    fail: 'No resistor → over-current burns it out instantly. Reverse bias → no light.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'K', x: 2, y: 0.5 }] },
  { id: 'diode', cat: 'electronics', name: 'Diode', w: 2, h: 1, icon: 'diode', sim: 'diode',
    desc: 'One-way valve for current; used for rectification and reverse-polarity protection.',
    how: 'A p-n junction conducts forward bias and blocks reverse bias.',
    spec: 'e.g. 1N4007: 1 A, 1000 V PIV',
    fail: 'Removed → reverse current can destroy sensitive parts.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'K', x: 2, y: 0.5 }] },
  { id: 'transistor', cat: 'electronics', name: 'Transistor (NPN)', w: 2, h: 2, icon: 'transistor', sim: 'transistor',
    desc: 'Electronic switch/amplifier — a small base current gates a much larger collector current.',
    how: 'Base-emitter voltage controls collector-emitter conduction; the core of all digital logic.',
    spec: 'e.g. 2N2222: 40 V, 800 mA, hFE 100',
    fail: 'Removed → the controlled load (LED/motor) cannot switch.',
    pins: [{ id: 'B', x: 1, y: 0 }, { id: 'C', x: 2, y: 1 }, { id: 'E', x: 0, y: 1 }] },
  { id: 'switch', cat: 'electronics', name: 'Toggle Switch', w: 2, h: 1, icon: 'switch', sim: 'switch',
    desc: 'Master power gate — opens and closes the current path by hand.',
    how: 'A spring contact bridge connects or severs two terminals. Double-click it to toggle open/closed.',
    spec: 'Rating: 250 V AC / 5 A',
    fail: 'Open → circuit interrupted, no power downstream.',
    pins: [{ id: 'IN', x: 0, y: 0.5 }, { id: 'OUT', x: 2, y: 0.5 }], extra: { state: 'closed' } },
  { id: 'fuse', cat: 'electronics', name: 'Fuse', w: 2, h: 1, icon: 'fuse', sim: 'fuse',
    desc: 'Sacrificial over-current protector — melts to break the circuit before damage.',
    how: 'A thin wire heats up and melts when current exceeds its rating.',
    spec: 'e.g. 1 A fast-blow',
    fail: 'Blows on short circuit — must be replaced.',
    pins: [{ id: 'IN', x: 0, y: 0.5 }, { id: 'OUT', x: 2, y: 0.5 }] },
  { id: 'inductor', cat: 'electronics', name: 'Inductor', w: 2, h: 1, icon: 'inductor', sim: 'inductor',
    desc: 'Stores energy in a magnetic field; resists sudden current changes.',
    how: 'Changing current induces a back-EMF that opposes it (Lenz\'s law).',
    spec: 'µH – mH, saturation current',
    fail: 'Removed → switching circuits get voltage spikes.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'motor', cat: 'electronics', name: 'DC Motor', w: 2, h: 2, icon: 'motor', sim: 'motor',
    desc: 'Converts electrical energy into rotary motion — the actuator of the system.',
    how: 'Current in the armature interacts with the magnetic field to produce torque.',
    spec: '3–12 V, 100–2000 mA, RPM variable',
    fail: 'No power → no rotation. Reversed polarity → spins the wrong way.',
    pins: [{ id: '+', x: 1, y: 0 }, { id: '-', x: 1, y: 2 }] },
  { id: 'buzzer', cat: 'electronics', name: 'Buzzer', w: 2, h: 1, icon: 'buzzer', sim: 'buzzer',
    desc: 'Audio alert output — beeps when powered.',
    how: 'A piezoelectric element or coil pushes a diaphragm at its resonant frequency.',
    spec: '5 V, 85 dB @ 2 kHz',
    fail: 'No power → silent.',
    pins: [{ id: '+', x: 0, y: 0.5 }, { id: '-', x: 2, y: 0.5 }] },
  { id: 'speaker', cat: 'electronics', name: 'Speaker', w: 2, h: 1, icon: 'speaker', sim: 'speaker',
    desc: 'Audio output stage — turns an electrical signal into sound waves.',
    how: 'Voice coil in a magnetic field pushes a cone to create pressure waves.',
    spec: '8 Ω, 0.5 W',
    fail: 'No signal → silent. Reverse voltage → distorted.',
    pins: [{ id: '+', x: 0, y: 0.5 }, { id: '-', x: 2, y: 0.5 }] },
  { id: 'relay', cat: 'electronics', name: 'Relay', w: 3, h: 2, icon: 'relay', sim: 'relay',
    desc: 'Electromechanical switch — a small coil current switches a large load.',
    how: 'Coil energizes an electromagnet that pulls a contact arm closed.',
    spec: '5 V coil, 250 V/10 A contacts',
    fail: 'Coil no power → contacts stay open.',
    pins: [{ id: 'C+', x: 0, y: 0.5 }, { id: 'C-', x: 0, y: 1.5 }, { id: 'COM', x: 3, y: 0.5 }, { id: 'NO', x: 3, y: 1.5 }] },
  { id: 'button', cat: 'electronics', name: 'Push Button', w: 2, h: 1, icon: 'button', sim: 'button',
    desc: 'Momentary switch — conducts only while pressed (treated as closed).',
    how: 'A spring returns the contact after release.',
    spec: '12 V / 50 mA momentary',
    fail: 'Released → breaks the signal path.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'potentiometer', cat: 'electronics', name: 'Potentiometer', w: 2, h: 1, icon: 'potentiometer', sim: 'resistor',
    desc: 'Adjustable resistor — a knob changes the resistance value (acts as a current limiter).',
    how: 'A wiper slides along a resistive track, dividing the resistance.',
    spec: '10 kΩ linear / audio taper',
    fail: 'Acts like a resistor; extreme setting can starve the circuit.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'ldr', cat: 'electronics', name: 'Light Sensor (LDR)', w: 2, h: 1, icon: 'ldr', sim: 'resistor',
    desc: 'Light-dependent resistor — resistance drops when light hits it.',
    how: 'Photons free charge carriers in cadmium sulfide, lowering resistance.',
    spec: '1 MΩ dark → 100 Ω bright',
    fail: 'In a divider it changes threshold; here acts as a (light-dependent) resistor.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'seg7', cat: 'electronics', name: '7-Segment Display', w: 2, h: 2, icon: 'seg7', sim: 'seg7',
    desc: 'Numeric display — shows digits when powered by the controller.',
    how: 'Seven LED bars light in patterns to form 0–9 and letters.',
    spec: 'Common cathode / common anode, 20 mA/seg',
    fail: 'No power → blank.',
    pins: [{ id: 'VCC', x: 1, y: 0 }, { id: 'GND', x: 1, y: 2 }] },
  { id: 'ic', cat: 'electronics', name: 'Op-Amp IC', w: 3, h: 2, icon: 'ic', sim: 'ic',
    desc: 'Integrated circuit that conditions and amplifies signals between blocks.',
    how: 'Thousands of on-die transistors amplify the difference between its inputs.',
    spec: 'e.g. LM358 dual op-amp, 3–32 V',
    fail: 'No power → no signal amplification.',
    pins: [{ id: 'VCC', x: 1, y: 0 }, { id: 'GND', x: 1, y: 2 }, { id: 'IN', x: 0, y: 1 }, { id: 'OUT', x: 3, y: 1 }] },
  { id: 'mcu', cat: 'electronics', name: 'Microcontroller', w: 3, h: 2, icon: 'mcu', sim: 'mcu',
    desc: 'The brain — runs a program that reads inputs and drives outputs.',
    how: 'A CPU executes stored instructions from flash memory at millions of cycles/second.',
    spec: 'e.g. ATmega328P / ESP32, 5 V logic',
    fail: 'No power → no program, system stops thinking.',
    pins: [{ id: 'VCC', x: 1, y: 0 }, { id: 'GND', x: 1, y: 2 }, { id: 'IN', x: 0, y: 1 }, { id: 'OUT', x: 3, y: 1 }] },
  { id: 'crystal', cat: 'electronics', name: 'Crystal Oscillator', w: 2, h: 1, icon: 'crystal', sim: 'crystal',
    desc: 'Precise clock source that keeps the MCU timing accurate.',
    how: 'A quartz crystal vibrates at an exact frequency; the MCU counts its cycles.',
    spec: '16 MHz HC-49',
    fail: 'Removed → MCU has no clock.',
    pins: [{ id: 'A', x: 0, y: 0.5 }, { id: 'B', x: 2, y: 0.5 }] },
  { id: 'regulator', cat: 'electronics', name: 'Voltage Regulator', w: 3, h: 2, icon: 'regulator', sim: 'regulator',
    desc: 'Converts an unstable higher voltage into a fixed stable output rail.',
    how: 'Internal feedback adjusts a pass transistor to hold the output voltage.',
    spec: 'e.g. 7805 → 5 V / 1 A',
    fail: 'No input → no output, downstream starved.',
    pins: [{ id: 'IN', x: 0, y: 1 }, { id: 'GND', x: 1.5, y: 2 }, { id: 'OUT', x: 3, y: 1 }] },
  { id: 'transformer', cat: 'electronics', name: 'Transformer', w: 3, h: 2, icon: 'transformer', sim: 'transformer',
    desc: 'Steps AC voltage up or down using magnetic coupling.',
    how: 'AC in the primary induces voltage in the secondary; the turn ratio sets the output.',
    spec: '230 V → 9 V, 1 A',
    fail: 'Removed → no converted voltage.',
    pins: [{ id: 'P1', x: 0, y: 0.5 }, { id: 'P2', x: 0, y: 1.5 }, { id: 'S1', x: 3, y: 0.5 }, { id: 'S2', x: 3, y: 1.5 }] },
  { id: 'antenna', cat: 'electronics', name: 'Antenna', w: 1, h: 2, icon: 'antenna', sim: 'antenna',
    desc: 'Radiates and receives radio-frequency signals (wireless link).',
    how: 'A conductor matched to the wavelength converts RF energy to/from EM waves.',
    spec: '2.4 GHz quarter-wave',
    fail: 'Removed → no wireless link.',
    pins: [{ id: 'OUT', x: 0.5, y: 0 }] },
  { id: 'servo', cat: 'electronics', name: 'Servo Motor', w: 2, h: 2, icon: 'servo', sim: 'servo',
    desc: 'Precision position actuator — moves to a commanded angle from the MCU.',
    how: 'A geared DC motor + feedback pot positions the output shaft from a PWM signal.',
    spec: 'SG90 9 g, 180°, 4.8–6 V',
    fail: 'No signal → holds last position.',
    pins: [{ id: 'VCC', x: 1, y: 0 }, { id: 'GND', x: 1, y: 2 }, { id: 'SIG', x: 0, y: 1 }] },
  { id: 'display', cat: 'electronics', name: 'OLED Display', w: 3, h: 2, icon: 'display', sim: 'seg7',
    desc: 'Graphic screen that shows live data from the microcontroller.',
    how: 'Organic LEDs light per-pixel from the I2C/SPI controller.',
    spec: '128×64, 0.96" I2C',
    fail: 'No power → blank screen.',
    pins: [{ id: 'VCC', x: 1, y: 0 }, { id: 'GND', x: 1, y: 2 }] },

  // ============ MECHANICAL ============
  { id: 'gear', cat: 'mechanical', name: 'Spur Gear (12T)', w: 2, h: 2, icon: 'gear', sim: 'gear', attr: { teeth: 12 },
    desc: 'Tooth wheel that transfers rotary motion and torque between shafts.',
    how: 'Meshing teeth lock two shafts in a fixed ratio: output = input × teeth_in/teeth_out.',
    spec: 'Module 1, 12 teeth, Ø14 mm',
    fail: 'Not meshed → no drive. Stripped tooth → jerky motion.' },
  { id: 'gearLarge', cat: 'mechanical', name: 'Spur Gear (24T)', w: 2, h: 2, icon: 'gearLarge', sim: 'gear', attr: { teeth: 24 },
    desc: 'Large gear — meshed with a smaller one it multiplies torque and slows speed.',
    how: 'Gear ratio = 24/12 = 2:1 → double the torque, half the speed.',
    spec: 'Module 1, 24 teeth, Ø26 mm',
    fail: 'Not meshed → no drive.' },
  { id: 'shaft', cat: 'mechanical', name: 'Shaft', w: 3, h: 1, icon: 'shaft', sim: 'shaft', attr: { length: 60 },
    desc: 'Rotating cylindrical bar that carries torque between drive elements.',
    how: 'Twist along its length transfers torque; needs bearings to run smooth.',
    spec: 'Ø6 mm steel, 60 mm',
    fail: 'Unsupported → whips/wobbles at speed.' },
  { id: 'bearing', cat: 'mechanical', name: 'Bearing', w: 2, h: 2, icon: 'bearing', sim: 'bearing',
    desc: 'Supports a rotating shaft while minimizing friction.',
    how: 'Balls/rollers separate the races; rolling friction << sliding friction.',
    spec: '608ZZ: Ø8/Ø22/7 mm',
    fail: 'Missing → shaft binds or wears out.' },
  { id: 'spring', cat: 'mechanical', name: 'Compression Spring', w: 3, h: 1, icon: 'spring', sim: 'spring', attr: { force: 20 },
    desc: 'Stores mechanical energy and returns it — pushes back when compressed.',
    how: 'Helical coil deflects linearly per Hooke\'s law F = k·x.',
    spec: 'k = 5 N/mm, free length 30 mm',
    fail: 'Fatigue → loses force, sags.' },
  { id: 'pulley', cat: 'mechanical', name: 'Pulley (S)', w: 2, h: 2, icon: 'pulley', sim: 'pulley', attr: { radius: 1 },
    desc: 'Grooved wheel that transfers motion through a belt.',
    how: 'Belt friction drives the pulley; ratio = diameter2/diameter1.',
    spec: 'Ø12 mm, 3 mm groove',
    fail: 'Belt slips → lost speed.' },
  { id: 'pulleyLarge', cat: 'mechanical', name: 'Pulley (L)', w: 2, h: 2, icon: 'pulleyLarge', sim: 'pulley', attr: { radius: 2 },
    desc: 'Large pulley — with a small pulley gives a belt-drive speed reduction.',
    how: 'Ratio = 2:1 → torque doubles, speed halves.',
    spec: 'Ø24 mm, 3 mm groove',
    fail: 'Belt slips → lost speed.' },
  { id: 'belt', cat: 'mechanical', name: 'Drive Belt', w: 2, h: 2, icon: 'belt', sim: 'belt',
    desc: 'Loop that transmits power between two pulleys over a distance.',
    how: 'Friction between belt and grooves transfers torque; tension sets the grip.',
    spec: '3 mm round, 120 mm loop',
    fail: 'Slack/broken → no power transfer.' },
  { id: 'bolt', cat: 'mechanical', name: 'Bolt + Nut', w: 2, h: 2, icon: 'bolt', sim: 'bolt',
    desc: 'Threaded fastener that clamps parts together with high preload.',
    how: 'Turning the nut converts torque into clamping force along the thread.',
    spec: 'M5 × 0.8 mm pitch',
    fail: 'Loose → joints rattle and parts shift.' },
  { id: 'chassis', cat: 'mechanical', name: 'Chassis Frame', w: 3, h: 2, icon: 'chassis', sim: 'chassis',
    desc: 'Structural base that everything mounts on — the "skeleton" of the device.',
    how: 'Rigid frame holds parts in alignment and absorbs vibration.',
    spec: '2 mm Al, cut & bent',
    fail: 'Cracked → misalignment and resonance.' },
  { id: 'piston', cat: 'mechanical', name: 'Piston', w: 3, h: 1, icon: 'piston', sim: 'piston',
    desc: 'Converts pressure (or crank rotation) into linear motion.',
    how: 'Slides in a bore; linked to a crank it turns reciprocating into rotary.',
    spec: 'Ø20 mm, 30 mm stroke',
    fail: 'Unlinked → no motion output.' },
  { id: 'linkage', cat: 'mechanical', name: 'Linkage Rod', w: 3, h: 1, icon: 'linkage', sim: 'linkage',
    desc: 'Rigid bar with pivot joints that transmits force and motion between points.',
    how: 'A 4-bar linkage converts rotation into walking/translating motion.',
    spec: '4-bar mechanism, 40 mm links',
    fail: 'Unlinked → motion not transmitted.' },
  { id: 'hinge', cat: 'mechanical', name: 'Hinge', w: 2, h: 2, icon: 'hinge', sim: 'hinge',
    desc: 'Pivot joint allowing one rotational degree of freedom.',
    how: 'Two leaves rotate around a shared pin.',
    spec: 'Door/panel hinge, steel',
    fail: 'Seized → cannot rotate.' },
  { id: 'coupling', cat: 'mechanical', name: 'Coupling', w: 3, h: 1, icon: 'coupling', sim: 'coupling',
    desc: 'Joins two shafts end-to-end to transmit torque while allowing small misalignment.',
    how: 'Friction jaws or flexible element transfer rotation between shaft ends.',
    spec: 'Clamp type Ø6 mm',
    fail: 'Missing → shafts cannot join.' },
  { id: 'cam', cat: 'mechanical', name: 'Cam', w: 2, h: 2, icon: 'cam', sim: 'cam',
    desc: 'Eccentric lobe that converts rotation into a programmed linear motion.',
    how: 'A follower rides the cam profile; lobe shape defines the motion curve.',
    spec: 'Eccentric 8 mm, 20 mm lobe',
    fail: 'Not on shaft → no motion profile.' },
  { id: 'gearbox', cat: 'mechanical', name: 'Gearbox Housing', w: 3, h: 2, icon: 'gearbox', sim: 'gearbox',
    desc: 'Sealed case that holds gear trains, oil, and alignment.',
    how: 'Contains and lubricates the gear train, multiplying torque safely.',
    spec: '3-stage reduction, 60:1',
    fail: 'No housing → gears unsupported.' },
  { id: 'washer', cat: 'mechanical', name: 'Washer', w: 2, h: 2, icon: 'washer', sim: 'washer',
    desc: 'Thin plate under a bolt head that spreads load and prevents loosening.',
    how: 'Increases contact area; spring washers add preload to resist vibration.',
    spec: 'M5 plain / split-lock',
    fail: 'Missing → fastener loosens.' },
  { id: 'joint', cat: 'mechanical', name: 'Universal Joint', w: 2, h: 2, icon: 'joint', sim: 'joint',
    desc: 'Connects two shafts at an angle, transmitting rotation through a bend.',
    how: 'Two yokes + a cross spider absorb angular misalignment.',
    spec: 'Ø6 mm, 30° max angle',
    fail: 'Missing → shafts cannot bend.' },
  { id: 'motorMount', cat: 'mechanical', name: 'Motor Mount', w: 3, h: 1, icon: 'motorMount', sim: 'motorMount',
    desc: 'Bracket that clamps a motor in place and keeps it aligned to the drive.',
    how: 'Precision holes/index align the motor to the pulley or gear.',
    spec: 'NEMA-17 / 28BYJ mount',
    fail: 'Loose → vibration and misalignment.' },
  { id: 'leadScrew', cat: 'mechanical', name: 'Lead Screw', w: 3, h: 1, icon: 'leadScrew', sim: 'leadScrew',
    desc: 'Threaded rod that converts rotation into precise linear travel.',
    how: 'A nut travels one pitch per turn — very high positioning accuracy.',
    spec: 'T8 × 2 mm pitch',
    fail: 'No motor → no linear drive.' }
];

export function getAsset(id) {
  return ASSETS.find(a => a.id === id);
}

export function iconSvg(iconName) {
  return (ICONS[iconName] || (() => ''))();
}
